### ISSUE TITLE
Unable to communicate with the library - Unhandled exception error

### ISSUE THREAD

**Issue by edif** [enigma-dev/lgmplugin#32] opened 2015-03-24 14:03 UTC
![enigma_message](https://cloud.githubusercontent.com/assets/6934810/6803184/d5b39b90-d22d-11e4-8ab5-9a11298cec80.png)

"Unhandled Exception"

Error report:

Operating System: Windows 7
Version: 6.1
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.8.0_40

Available processors (cores): 2
Free memory (bytes): 208285904
Maximum memory (bytes): 932184064
Total memory available to JVM (bytes): 257425408

File system root: C:\
Total space (bytes): 1000097181696
Free space (bytes): 930561708032
Usable space (bytes): 930561708032

File system root: D:\
Total space (bytes): 249997291520
Free space (bytes): 155372744704
Usable space (bytes): 155372744704

File system root: E:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: F:\
Total space (bytes): 15487131648
Free space (bytes): 13588545536
Usable space (bytes): 13588545536

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf': Native library (win32-x86-64/compileEGMf.dll) not found in resource path ([file:/C:/Users/user/Desktop/Enigma/ENIGMA/enigma-dev/plugins/enigma.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:247)
	at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:240)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:178)

**Comment by RobertBColton** [comment] 2015-09-25 00:55
@edif Hello, are you by chance running a 64 bit Java installation? The ENIGMA plugin only supports 32 bit for Windows currently.

**Comment by RobertBColton** [comment] 2015-10-03 09:24
Closing as duplicate of #20

**Closed by RobertBColton** 2015-10-03 09:24 UTC
