### ISSUE TITLE
[SOLVED] Can't start ENIGMA. This error pops out.

### ISSUE THREAD

**Issue by PranavGM** [enigma-dev/lgmplugin#61] opened 2018-06-05 03:56 UTC
LateralGM Version: 1.8.40

Operating System: Linux
Version: 4.4.0-116-generic
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_171

Available processors (cores): 4
Free memory (bytes): 81246216
Maximum memory (bytes): 1605369856
Total memory available to JVM (bytes): 100663296

File system root: /
Total space (bytes): 977073426432
Free space (bytes): 857000620032
Usable space (bytes): 807344570368

Stack trace:

java.lang.ExceptionInInitializerError
	at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:68)
	at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:59)
	at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:395)
	at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:1)
	at org.lateralgm.main.LGM$SingletonPluginResource.getResourceHolder(LGM.java:962)
	at org.lateralgm.main.LGM.addPluginResource(LGM.java:923)
	at org.enigma.EnigmaRunner.addResourceHook(EnigmaRunner.java:350)
	at org.enigma.EnigmaRunner.<init>(EnigmaRunner.java:134)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.lateralgm.main.LGM.loadPlugins(LGM.java:719)
	at org.lateralgm.main.LGM.main(LGM.java:1190)
Caused by: java.lang.IndexOutOfBoundsException: Name
	at org.enigma.file.YamlParser$YamlNode.getM(YamlParser.java:61)
	at org.enigma.file.YamlParser$YamlNode.getMC(YamlParser.java:68)
	at org.enigma.TargetHandler.findCompilers(TargetHandler.java:280)
	at org.enigma.TargetHandler.load(TargetHandler.java:57)
	at org.enigma.TargetHandler.<clinit>(TargetHandler.java:51)
	... 15 more

**Comment by RobertBColton** [comment] 2018-06-05 16:49
@PranavGM did you obtain the 1.8.7.11 enigma.jar LGM plugin? The LGM version is always ahead of its ENIGMA plugin version. The version of the ENIGMA plugin is the minimum version of LGM required to use that plugin. So if you downloaded LGM 1.8.40 (which your log here says) then you need to grab the 1.8.7.11 plugin: https://github.com/enigma-dev/lgmplugin/releases

The file `enigma.jar` should be placed in `enigma-dev/plugins/enigma.jar` and it should fix this.

**Comment by PranavGM** [comment] 2018-06-05 17:59
@RobertBColton I did get the 1.8.7.11 plugin, but it still gives me the same error. I also decided to download an older version of LGM (1.8.32) but it still didn't work. By the way, I'm okay to use Radial or Sharp GM. The problem is, their builds are not available because its a work in progress and I can't compile it by myself because I don't have the software.

**Comment by RobertBColton** [comment] 2018-06-05 18:34
Well, I can say at this point, building games with the LGM setup is still probably the most feature complete. However, going the RadialGM route, I can actually show you how to work emake right now. RadialGM is being designed to communicate with ENIGMA using emake in server mode for IPC. So emake is basically replacing the middleman, lgmplugin here.

emake is handling both GMX and GMK perfect right now, as I am using it constantly and so is the continuous integration on every pr, but we need to still iron out some EGM stuff. I will show you both of the routes, and you can decide for yourself. If you go with the emake setup (preparing you for a RadialGM beta) you can still install LGM on top of that too and have both.

### Continue with this LateralGM setup
This may be a new issue with the lgmplugin since fundies made some recent changes to the compiler ey files: https://github.com/enigma-dev/enigma-dev/pull/1250
If you know how to work Git, you could try reverting to a commit on master before that pr was merged.

Your errors also mimic those that I've seen others having with this specific Java version. I did recently tweak LGM to work with Java 9, so you could try that as well, however there may be new issues (depending on your platform). While we're at it, LateralGM also has a lot less issues with the Oracle JDK than OpenJDK. I understand that the Oracle JDK is proprietary, but giving it a try may also solve your issues here.

The first thing I would try here is the Oracle JDK 8.

### Try out emake
So the setup is basically the same, with some additional dependencies and compilation steps. I've, so far, only formalized the installation instructions for MSYS2 on Windows, but that basically just makes it like a Linux setup: https://enigma-dev.org/docs/Wiki/Install:Windows

Regardless, those steps may help you, because you will need equivalent packages for your platform for the Google Protocol Buffer compiler. You will need pugixml for libEGM to build GMX support, and rapidJSON is used for the YYP reader (which is not yet finished, I will be getting back to it soon).

I can gaurantee that this build currently works for Ubuntu Xenial because that is what ENIGMA's Travis CI is building it on right now: https://github.com/enigma-dev/enigma-dev/blob/0c5062e413e79c56a686f8bb6798d80acf5ac07f/.travis.yml#L17

So, you can reference that as well for setting up emake. You will also want a newer GCC, like GCC 7, because the GMK reader uses C++14 features for memory safety.

Finally, I've also written this guide explaining how emake is used: https://enigma-dev.org/docs/Wiki/Command_line_interface

Again, it's actually pretty simple, but you may get stuck, and if so, we'll be around to help. As I said, you can also setup LGM this route too, you just copy LGM and the lgmplugin in like you would normally and they can function side by side.

**Comment by PranavGM** [comment] 2018-06-06 02:53
@RobertBColton  Thank you so much for the detailed answer. I just can't get LGM to work. If I install Qt, will I be able to run RadialGM? Or is there a webpage where I can download RadialGM beta builds?

**Comment by RobertBColton** [comment] 2018-06-06 07:47
Not yet, you would have to manually build it from source (which honestly isn't that more complicated than setting up LGM) because we don't have installers yet. It's also going to be unusable for every day work until we finish more editors. Having installers for RadialGM is definitely something I want to do. For now, to fix your LateralGM, please see the directions above, you should attempt to install and set Oracle JDK 8 as your default Java.

**Comment by RobertBColton** [comment] 2018-06-07 03:19
Quick update on this, we did track this down to https://github.com/enigma-dev/enigma-dev/pull/1250 and have temporarily reverted the change. If you do a git pull of ENIGMA master and try LateralGM again, it should be working now.

**Comment by PranavGM** [comment] 2018-06-10 04:50
Guess what? It friggin' werks. YOU'RE SUCH A GENIUS! I can finally work in game maker, the engine i grew up with in LINUX!!! THX AGAIN!

**Comment by RobertBColton** [comment] 2018-06-10 08:30
You're welcome, and that's good news, sorry about the minor hickup, there will be some great things yet to come.

**Comment by RobertBColton** [comment] 2018-06-20 02:57
This has further been resolved by #63

The next time you set up ENIGMA or if you happen to do a `git pull` you'll just need to obtain the newer `enigma.jar` because we have decided to redo those changes again, but this time updating the plugin to make it compatible. You may also need to `make clean` in the enigma-dev folder after this.
https://github.com/enigma-dev/lgmplugin/releases/tag/v1.8.7.11r2

**Comment by RemoveRusky** [comment] 2018-06-20 17:43
still broke see #63

**Closed** 2018-06-21 00:11 UTC

**Comment by RobertBColton** [comment] 2018-06-21 03:02
I've sent https://github.com/enigma-dev/enigma-dev/pull/1286 to fix your mistakes we missed, Hugar has tested them and confirmed they fix the continuing issues caused by you.
