### ISSUE TITLE
Unable to load library 'compileEGMf': Native library (linux-x86/libcompileEGMf.so) not found in resource path

### ISSUE THREAD

**Issue by macosten** [enigma-dev/lgmplugin#49] opened 2016-09-13 02:43 UTC
Tried getting this to work for ~2 hours, I think it's about time I posted an issue here and asked for help...

List of things I've tried (that I can remember):
    Actually place libcompileEGMf.so into enigma.jar (That crashes with "can't find input stream for...")
    use 64 bit and 32 bit JREs
    use Java 8 and Java SE 7 (java 8 appears to be unsupported anyway; it was crashing differently)
    Compile while having JRE 7 enabled
    Make sure all dependencies are installed (maybe I missed some? I don't know.)
# Not sure what's going wrong here.

Operating System: Linux
Version: 4.7.2-201.fc24.x86_64
Architecture: i386

Java Name: OpenJDK Server VM
Java Vendor: Oracle Corporation
Version: 1.7.0_65

Available processors (cores): 8
Free memory (bytes): 46665616
Maximum memory (bytes): 954466304
Total memory available to JVM (bytes): 81788928

File system root: /
Total space (bytes): 52710469632
Free space (bytes): 34449162240
Usable space (bytes): 31748030464

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf': Native library (linux-x86/libcompileEGMf.so) not found in resource path ([file:/home/zac/Applications/enigma-dev/plugins/enigma.jar])
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
    at com.sun.jna.Library$Handler.<init>(Library.java:147)
    at com.sun.jna.Native.loadLibrary(Native.java:412)
    at com.sun.jna.Native.loadLibrary(Native.java:391)
    at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:248)
    at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:241)
    at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:179)

**Comment by RobertBColton** [comment] 2016-09-13 06:10
What is your distro?

**Comment by macosten** [comment] 2016-09-13 06:53
Fedora 24 (fc24_x64). 

I did not have JNA installed before (downloaded and installed it: sudo dnf install jna*, installed jna, jna-contrib, and jna-javadoc). I then did a make clean && make but I'm still getting the same exact error.


If this helps at all, here is the error I get when I put compileEGMf into enigma.jar:

Operating System: Linux
Version: 4.7.2-201.fc24.x86_64
Architecture: i386

Java Name: OpenJDK Server VM
Java Vendor: Oracle Corporation
Version: 1.7.0_65

Available processors (cores): 8
Free memory (bytes): 44522008
Maximum memory (bytes): 954466304
Total memory available to JVM (bytes): 81788928

File system root: /
Total space (bytes): 52710469632
Free space (bytes): 34645630976
Usable space (bytes): 31944499200

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf': Can't obtain InputStream for linux-x86/libcompileEGMf.so
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:248)
	at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:241)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:179)

**Comment by RobertBColton** [comment] 2016-09-13 07:09
Oh I noticed you didn't mention whether you tried the Oracle JDK. I notice you are using OpenJDK which actually has a number of issues in LGM. Can you please try downloading the Oracle JDK? It does not matter if 32 bit or 64 bit, but make sure you launch LGM with the Oracle JDK and not OpenJDK.

**Comment by fundies** [comment] 2016-09-13 07:11
why are you trying to place .so inside the jar? You don't move the .so file at all...

**Comment by macosten** [comment] 2016-09-13 16:55
> why are you trying to place .so inside the jar? You don't move the .so file at all...
I figure it was a futile attempt to do what the error appeared to want: put a resource somewhere that it wanted to be. 

>Can you please try downloading the Oracle JDK? It does not matter if 32 bit or 64 bit, but make sure you launch LGM with the Oracle JDK and not OpenJDK.

Ah, I had tried both Java 7 (but openJDK) and Oracle's JDK (but it was Java 8).

Under this version (Oracle's JDK, Version 7, 64-bit) it's actually giving me issues similar to the problems I had at the beginning of my attempts at getting Enigma to work. The LateralGM window appears for about three seconds and then closes itself.

Here's my console output.


Process terminated
Initializing Enigma: 
Failed to create make directory at /home/zac/.enigma/
Make directory is: "/home/zac/.enigma/"
Linking up to IDE
Implementing JDI basics
UnimplementedUnimplemented

Choosing language: C++
Reading GCC builtins
Read key `defines` as `cpp -dM -x c++ -E $blank`
Parsed `cpp` `-dM -x c++ -E "/home/zac/.enigma/enigma_blank.txt"`: redirect=yes
TRUE




*********** EXECUTE 
  `/usr/bin/cpp`
  `-dM`
  `-x`
  `c++`
  `-E`
  `/home/zac/.enigma/enigma_blank.txt`



Call succeeded
Read key `searchdirs` as `gcc -E -x c++ -v $blank`
Parsed `gcc` `-E -x c++ -v "/home/zac/.enigma/enigma_blank.txt"`: redirect=yes
TRUE




*********** EXECUTE 
  `/usr/bin/gcc`
  `-E`
  `-x`
  `c++`
  `-v`
  `/home/zac/.enigma/enigma_blank.txt`



Call succeeded
Searching for directories between "#include <...> search starts here:" and "End of search list."
Toolchain returned 8 search directories:
Creating parse context
Parsing settings...
TOINT: 0
TOINT: 0
TOINT: 1
TOINT: 0
TOINT: 0
TOINT: 0
Setting up IDE editables... 
%e-yaml
---
treat-literals-as: 0
make-directory: "%HOME%/.enigma/"
inherit-strings-from: 0
automatic-semicolons: true
inherit-equivalence-from: 0
compliance-mode: 0
scalar-precision: 0
angular-unit: 0
inherit-escapes-from: 0
inherit-negatives-as: 0
inherit-objects: true
inherit-increment-from: 1
keyword-blacklist: ""

target-networking: None
target-audio: OpenAL
target-windowing: xlib
target-compiler: gcc
target-graphics: OpenGL1
target-widget: None
target-collision: Precise

extensions: Universal_System/Extensions/Alarms,Universal_System/Extensions/Timelines,Universal_System/Extensions/Paths,Universal_System/Extensions/BasicGUI,Universal_System/Extensions/MotionPlanning,Universal_System/Extensions/DateTime,Universal_System/Extensions/ParticleSystems,Universal_System/Extensions/DataStructures

Creating swap.
Dumping whiteSpace definitions...
Opening ENIGMA for parse...
Unimplemented: '::'#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2b138875e4, pid=20594, tid=139822994065152
#
# JRE version: Java(TM) SE Runtime Environment (7.0_79-b15) (build 1.7.0_79-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.79-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libcompileEGMf.so+0x1295e4]  jdip::read_qualified_definition(jdi::lexer*, jdi::definition_scope*, jdip::token_t&, jdip::context_parser*, jdi::error_handler*)+0xf1
#
# Core dump written. Default location: /home/zac/Applications/enigma-dev/core or core.20594
#
# An error report file with more information is saved as:
# /home/zac/Applications/enigma-dev/hs_err_pid20594.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)

**Comment by RobertBColton** [comment] 2016-09-13 18:29
Yeah that is right where you need to be, this is now a known bug we are trying to get fixed.

Please try the workaround posted on the forum:
http://enigma-dev.org/forums/index.php?topic=2669.msg25839#msg25839

**Comment by macosten** [comment] 2016-09-14 03:50
...still broken, somehow. Tried multiple times, too. I wish I knew what I was.

...sorry for the incoming textual gargantuan and its terrible formatting. 

Interestingly, it now gives me tmultiple different errors.

...see the attached text file; GitHub would have formatting that made this unreadable otherwise.

[Enigma1.txt](https://github.com/enigma-dev/lgmplugin/files/471242/Enigma1.txt)

**Comment by RobertBColton** [comment] 2016-09-14 04:02
No thank you I appreciate that actually. I like it when people upload the text files as it makes it easier for everyone to read issues. People don't do this as often as I'd like though :smile: 

Can you try one thing for me real quick? Make a backup copy of the folder enigma-dev/ENIGMAsystem/SHELL/Universal_System/Extensions somewhere on your desktop or something. Then delete all the folder inside that Extensions folder. Finally, try launching ENIGMA/LGM again and let me know what happens.

Please keep an eye on https://github.com/enigma-dev/enigma-dev/issues/944 which is the original issue and we are trying to fix.

**Comment by macosten** [comment] 2016-09-14 04:11
Emptied out the Extensions folder after copying it (to 2 places, just to be sure)

I'm even testing this on separate java versions now. Not much of a difference, it seems, other than loading time.

[Enigma2.txt](https://github.com/enigma-dev/lgmplugin/files/471256/Enigma2.txt)

That's what happens - not much. Did a make clean && make; tried again; same result.

The Extensions folder is still empty, too.

**Comment by macosten** [comment] 2016-09-14 04:14
...looking at the old issue, it appears this is a problem that just suddenly appeared one day with some new version of Java. Perhaps it will work in Java 6...?

**Comment by RobertBColton** [comment] 2016-09-14 04:14
Hrm.... well I will note this time it made it a little further before crashing:
```
Unimplemented: '::'ERROR(ENIGMAsystem/SHELL/Graphics_Systems/graphics_mandatory.h,22,78): Could not find Universal_System/Extensions/ParticleSystems/PS_particle_instance.h
  Checked ENIGMAsystem/SHELL/Graphics_Systems
  Checked ENIGMAsystem/SHELL/
  Checked /home/zac/.enigma/
  Checked /usr/lib/gcc/x86_64-redhat-linux/6.1.1/../../../../include/c++/6.1.1/
  Checked /usr/lib/gcc/x86_64-redhat-linux/6.1.1/../../../../include/c++/6.1.1/x86_64-redhat-linux/
  Checked /usr/lib/gcc/x86_64-redhat-linux/6.1.1/../../../../include/c++/6.1.1/backward/
  Checked /usr/lib/gcc/x86_64-redhat-linux/6.1.1/include/
  Checked /usr/local/include/
  Checked /usr/include/
```
Before it was crashing right after ``Unimplemented '::'``

The only other suggestion I have right now would be to delete compileEGMf and downgrade to GCC 4.8.2 (what I am using on Windows) then make and make clean and run again.

And yes you can feel free to try Java 6 as well, even weirder is that it seems to only be happening to Arch users.

**Comment by macosten** [comment] 2016-09-14 04:26
Java 6 has a completely different error:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/lateralgm/main/LGM : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: org.lateralgm.main.LGM. Program will exit.

Gonna try the alternate GCC version.

**Comment by macosten** [comment] 2016-09-14 20:20
I gave up on that. An easier solution was just to set up a Virtual Machine with Ubuntu inside and use the script on the wiki to configure it.

Interesting that it works there but on in my main OS. Oh well.

**Comment by fundies** [comment] 2016-09-15 00:50
Enigmas broken on newer gcc's i dunno exactly what version it breaks at but it works on 4.9 for me and the portable zip has 4.8.2

**Comment by RobertBColton** [comment] 2016-09-15 01:03
He's not using Windows he's using Linux. Anyway, thank you @macosten I will try to keep you informed of a fix for this issue.

**Comment by fundies** [comment] 2016-09-15 01:08
my response was for linux you dumbass

**Comment by RobertBColton** [comment] 2017-09-30 02:43
This issue hasn't been fixed just yet, we're working on it right now. But I am going to close this ticket as a duplicate of the following:
https://github.com/enigma-dev/enigma-dev/issues/944

That ticket was first to report this issue and has been ongoing for longer, so please follow it for any updates about this JDI on newer gcc's issue. If you discover any completely new or different issues from the above, please post a new separate ticket for those. Thanks!

**Closed by RobertBColton** 2017-09-30 02:43 UTC
