### ISSUE TITLE
Feature: Cancel compile

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/lgmplugin#48] opened 2016-06-19 17:32 UTC
It would be really useful to be able to cancel compilation, sometimes I start compiling and remember that I forgot something and I have to wait until the compile finishes to recompile it again.

**Comment by RobertBColton** [comment] 2016-09-12 08:34
Sorry I did not see this but it is actually a duplicate of #2. I actually might get around to adding this cancel button soon too. All it has to do is check for it while looping all the resources being passed to compileEGMf and if its in the compile phase it should send a signal so compileEGMf can send a stop signal to make.

**Closed by RobertBColton** 2016-09-12 08:34 UTC
Labels: Enhancement, Task
